### ISSUE TITLE
Assets with no `v` prefix fails

### ISSUE THREAD

**Issue by kaitmore** [greymatter-io/gmenv#24]
We recently modified our build assets so that the version names do not contain a v prefix: https://github.com/greymatter-io/greymatter/issues/433

This breaks gmenv:

```GMENV_REPO=development gmenv install 2.0.0
Installing Grey Matter v2.0.0
Downloading release tarball from https://nexus.greymatter.io/repository/raw/development/gm-cli/greymatter-v2.0.0.tar.gz
#=O#-   #       #
curl: (22) The requested URL returned error: 404
Tarball download failed
```

from @chrisbsmith 
> yup.  there are tools built in to test.  though it may need some smarts to determine if there’s a v or not, so it’ backwards compatible with versions that contain a v

**Comment by dborncamp** [comment]
These lines appear to be the culprit https://github.com/greymatter-io/gmenv/blob/754f4309206b0914e9dfdc0dd6bc1ad6c0f6e160/libexec/gmenv-install#L86-L89

**Comment by chrisbsmith** [comment]
This line may be stripping out the `v` on the request to the nexus.  Worth exploring here and the line where Dave pointed out above.
