### ISSUE TITLE
Allow pre-release versions?

### ISSUE THREAD

**Issue by dontlaugh** [greymatter-io/gmenv#28]
It would be useful to fetch development versions that are, nonetheless, uploaded to our binary store.

**Comment by chrisbsmith** [comment]
@dontlaugh , `gmenv` allows you to set a [GMENV_REPO](https://github.com/greymatter-io/gmenv#gmenv_repo) env var to direct installation between `release` and `development`. If you're looking for pre-development releases, we could certainly add a third flag to denote a different repo.

**Comment by dontlaugh** [comment]
This worked swimmingly. I was on a machine w/o my dotfiles.
